services:
  - type: web
    name: socialcare-website
    runtime: node
    plan: free
    buildCommand: npm install --prefix client && npm run build --prefix client -- --outDir ../server/dist && npm install --prefix server
    startCommand: node server/server.js
    healthCheckPath: /api/healthcheck